# Generated by Django 6.0.5 on 2026-06-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_alter_taxrecord_tax_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ចំណងជើង')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='ឈ្មោះ URL')),
                ('summary', models.TextField(blank=True, verbose_name='សង្ខេប')),
                ('content', models.TextField(verbose_name='ខ្លឹមសារ')),
                ('category', models.CharField(choices=[('law', 'ច្បាប់ និងបទប្បញ្ញត្តិ'), ('deadline', 'កាលបរិច្ឆេទកំណត់'), ('tip', 'គន្លឹះពន្ធ'), ('update', 'ការផ្លាស់ប្តូរថ្មី'), ('general', 'ព័ត៌មានទូទៅ')], default='general', max_length=20, verbose_name='ប្រភេទ')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='ប្រភព')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='ពិសេស')),
                ('published_date', models.DateField(verbose_name='កាលបរិច្ឆេទចេញផ្សាយ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ព័ត៌មានពន្ធ',
                'verbose_name_plural': 'ព័ត៌មានពន្ធ',
                'ordering': ['-is_pinned', '-published_date'],
            },
        ),
    ]
